#General
spring.application.name=FitnessExerciseApp
server.port=${PORT:8080}

#Database settings
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=FitnessExerciseApp

#Cache settings
spring.cache.type=hazelcast

# Enable Swagger UI
springdoc.swagger-ui.enabled=true
